version: "3.9"

services:
  php-fpm:
    networks:
      - backend
    build:
      context: .
      dockerfile: ./etc/phpfpm.Dockerfile
      args:
        - DA_DEBUG=true
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html:cached
      - ./etc/phpfpm:/usr/local/etc/php/custom.d
      - /var/www/html/.git
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE}"
      DA_DEBUG: "true"
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
      XDEBUG_CONFIG: "client_host=${XDEBUG_REMOTE_HOST} client_port=9020 start_with_request=yes"

  mysql:
    image: mysql:oracle
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=password
    ports:
      - "3310:3306"
    volumes:
      - ./var/mysql-data:/var/lib/mysql:cached
    networks:
      - backend

  nginx:
    networks:
      - backend
    image: nginx:latest
    links:
      - php-fpm
    volumes:
      - ./public:/var/www/html/public:cached
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:cached
    ports:
      - "2000:80"
    expose:
      - 80

networks:
  backend:
    name: backend
    driver: bridge